name: FinInG
version: "1.5.1"
license: "GPL-2.0-or-later"
date: 2022-09-21
description: |
    Finite Incidence Geometry

authors:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Anton Betten
      url: http://www.math.colostate.edu/~betten
    - name: Philippe Cara
      url: http://homepages.vub.ac.be/~pcara
    - name: Jan De Beule
      url: http://www.debeule.eu
    - name: Michel Lavrauw
      url: http://people.sabanciuniv.edu/~mlavrauw/
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

maintainers:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Philippe Cara
      url: http://homepages.vub.ac.be/~pcara
    - name: Jan De Beule
      url: http://www.debeule.eu
    - name: Michel Lavrauw
      url: http://people.sabanciuniv.edu/~mlavrauw/
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.10"

needed-pkgs:
    - name: "cvec"
      version: ">=2.7.6"
      url: "https://gap-packages.github.io/cvec"
    - name: "Forms"
      version: ">=1.2.5"
      url: "https://gap-packages.github.io/forms"
    - name: "GAPDoc"
      version: ">= 1.6.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GenSS"
      version: ">=1.6.6"
      url: "https://gap-packages.github.io/genss"
    - name: "GRAPE"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/grape"
    - name: "Orb"
      version: ">=4.8.3"
      url: "https://gap-packages.github.io/orb"

www: https://gap-packages.github.io/FinInG
readme: README.md
packageinfo: https://gap-packages.github.io/FinInG/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/FinInG/releases/download/v1.5.1/fining-1.5.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/FinInG/releases/download/v1.5.1/fining-1.5.1.tar.bz2

abstract: |
    <span class="pkgname">FinInG</span> is a package for computation in Finite Incidence Geometry. It provides users with the basic tools to work in  various areas of finite geometry from the realms of projective spaces to the flat  lands of generalised polygons. The algebraic power of GAP is employed, particularly  in its facility with matrix and permutation groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    FinInG, finite, geometry.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BBCBLNH22</span>]   <b class='BibAuthor'>Bamberg, J., Betten, A., Cara, P., De Beule, J., Lavrauw, M., Neunhoeffer, M. and Horn, M.</b>,
     <i class='BibTitle'>FinInG, Finite Incidence Geometry,
             Version 1.5.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/FinInG">https://gap-packages.github.io/FinInG</a></span>.
    </p>
    

bibtex: |
    @misc{ FinInG1.5.1,
      author =           {Bamberg,  J. and Betten, A. and Cara, P. and De Beule,
                          J. and Lavrauw, M. and Neunhoeffer, M. and Horn, M.},
      title =            {{FinInG}, Finite Incidence Geometry, {V}ersion 1.5.1},
      month =            {Sep},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/FinInG}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{FinInG}}},
      keywords =         {FinInG; finite; geometry},
      printedkey =       {BBCBLNH22}
    }

